# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

# Note that this file is NOT used to automatically manage dependencies for the
# local compute target. To provision these dependencies locally, run:
# conda env update --file conda_dependencies.yml

# Details about the Conda environment file format:
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand

# For managing Spark packages and configuration, see spark_dependencies.yml.
# Version of this configuration file's structure and semantics in AzureML.
# This directive is stored in a comment to preserve the Conda file structure.
# [AzureMlVersion] = 2

name: flower_training_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - joblib=0.16.*
  - pillow=7.2.*
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk==1.13.*

      - azureml-contrib-services==1.13.*

      # Minimum required for the scoring environment. Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults==1.13.*

      # Training deps
      - tensorflow==2.3.*
      - keras==2.4.*
