name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - tqdm
    - numpy
    - opencv-python-headless
    - mlflow==2.4.0
    - azureml-mlflow==1.48.0
    - mldesigner==0.1.0b4
    - azure-ai-ml==1.4.0
    - azure-identity==1.11.0
    - azureml-core==1.49.0
    - azureml-dataset-runtime>=1.49.0
    - pandas
    - scikit-learn
    - jsonlines