# for manual search configuration. For more information 
# https://learn.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models?
# view=azureml-api-2&tabs=cli#manually-sweeping-model-hyperparameters
search_space:
  - model_name:
      type: choice
      values: [yolov5]
    learning_rate:
      type: uniform
      min_value: 0.0001
      max_value: 0.01
    image_size:
      type: choice
      values: [640, 800]
    model_size:
      type: choice
      values: [small, medium]
    number_of_epochs:
      type: choice
      values: [50]
    tile_grid_size:
      type: choice
      values: [2x2, 3x2]
      
  - model_name:
      type: choice
      values: [fasterrcnn_resnet50_fpn]
    learning_rate:
      type: uniform
      min_value: 0.0001
      max_value: 0.001
    optimizer:
      type: choice
      values: [sgd, adam, adamw]
    min_size:
      type: choice
      values: [600, 800]
    tile_grid_size:
      type: choice
      values: [2x2, 3x2]
    number_of_epochs:
      type: choice
      values: [30]